

services:
  app:
    build: .
    ports:
      - "${PORT}:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}  # Use local PostgreSQL connection
      - JWT_SECRET=${JWT_SECRET}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - TYPESENSEHOST=${TYPESENSEHOST}
      - TYPESENSEADMIN=${TYPESENSEADMIN}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_SERVICE_SID=${TWILIO_SERVICE_SID}
    depends_on:
      - minio
      - typesense
    volumes:
      - .:/app
    networks:
      - app-network

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data
    networks:
      - app-network

  typesense:
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSEADMIN}
      - TYPESENSE_HOST=${TYPESENSEHOST}
    ports:
      - "443:443"
    volumes:
      - typesense-data:/data
    networks:
      - app-network

volumes:
  minio-data:
  typesense-data:

networks:
  app-network:
